export const countries = [
  {
    name: "South Georgia",
    code: "GS",
    flag: "https://flagcdn.com/gs.svg",
    geoNameId: 3474415,
  },
  {
    name: "Grenada",
    code: "GD",
    flag: "https://flagcdn.com/gd.svg",
    geoNameId: 3580239,
  },
  {
    name: "Switzerland",
    code: "CH",
    flag: "https://flagcdn.com/ch.svg",
    geoNameId: 2658434,
  },
  {
    name: "Sierra Leone",
    code: "SL",
    flag: "https://flagcdn.com/sl.svg",
    geoNameId: 2403846,
  },
  {
    name: "Hungary",
    code: "HU",
    flag: "https://flagcdn.com/hu.svg",
    geoNameId: 719819,
  },
  {
    name: "Taiwan",
    code: "TW",
    flag: "https://flagcdn.com/tw.svg",
    geoNameId: 1668284,
  },
  {
    name: "Wallis and Futuna",
    code: "WF",
    flag: "https://flagcdn.com/wf.svg",
    geoNameId: 4034749,
  },
  {
    name: "Barbados",
    code: "BB",
    flag: "https://flagcdn.com/bb.svg",
    geoNameId: 3374084,
  },
  {
    name: "Pitcairn Islands",
    code: "PN",
    flag: "https://flagcdn.com/pn.svg",
    geoNameId: 4030699,
  },
  {
    name: "Ivory Coast",
    code: "CI",
    flag: "https://flagcdn.com/ci.svg",
    geoNameId: 2287781,
  },
  {
    name: "Tunisia",
    code: "TN",
    flag: "https://flagcdn.com/tn.svg",
    geoNameId: 2464461,
  },
  {
    name: "Italy",
    code: "IT",
    flag: "https://flagcdn.com/it.svg",
    geoNameId: 3175395,
  },
  {
    name: "Benin",
    code: "BJ",
    flag: "https://flagcdn.com/bj.svg",
    geoNameId: 2395170,
  },
  {
    name: "Indonesia",
    code: "ID",
    flag: "https://flagcdn.com/id.svg",
    geoNameId: 1643084,
  },
  {
    name: "Cape Verde",
    code: "CV",
    flag: "https://flagcdn.com/cv.svg",
    geoNameId: 3374766,
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    flag: "https://flagcdn.com/kn.svg",
    geoNameId: 3575174,
  },
  {
    name: "Laos",
    code: "LA",
    flag: "https://flagcdn.com/la.svg",
    geoNameId: 1655842,
  },
  {
    name: "Caribbean Netherlands",
    code: "BQ",
    flag: "https://flagcdn.com/bq.svg",
    geoNameId: 7626844,
  },
  {
    name: "Uganda",
    code: "UG",
    flag: "https://flagcdn.com/ug.svg",
    geoNameId: 226074,
  },
  {
    name: "Andorra",
    code: "AD",
    flag: "https://flagcdn.com/ad.svg",
    geoNameId: 3041565,
  },
  {
    name: "Burundi",
    code: "BI",
    flag: "https://flagcdn.com/bi.svg",
    geoNameId: 433561,
  },
  {
    name: "South Africa",
    code: "ZA",
    flag: "https://flagcdn.com/za.svg",
    geoNameId: 953987,
  },
  {
    name: "France",
    code: "FR",
    flag: "https://flagcdn.com/fr.svg",
    geoNameId: 3017382,
  },
  {
    name: "Libya",
    code: "LY",
    flag: "https://flagcdn.com/ly.svg",
    geoNameId: 2215636,
  },
  {
    name: "Mexico",
    code: "MX",
    flag: "https://flagcdn.com/mx.svg",
    geoNameId: 3996063,
  },
  {
    name: "Gabon",
    code: "GA",
    flag: "https://flagcdn.com/ga.svg",
    geoNameId: 2400553,
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    flag: "https://flagcdn.com/mp.svg",
    geoNameId: 4041468,
  },
  {
    name: "North Macedonia",
    code: "MK",
    flag: "https://flagcdn.com/mk.svg",
    geoNameId: 718075,
  },
  {
    name: "China",
    code: "CN",
    flag: "https://flagcdn.com/cn.svg",
    geoNameId: 1814991,
  },
  {
    name: "Yemen",
    code: "YE",
    flag: "https://flagcdn.com/ye.svg",
    geoNameId: 69543,
  },
  {
    name: "Saint Barthélemy",
    code: "BL",
    flag: "https://flagcdn.com/bl.svg",
    geoNameId: 3578476,
  },
  {
    name: "Guernsey",
    code: "GG",
    flag: "https://flagcdn.com/gg.svg",
    geoNameId: 3042362,
  },
  {
    name: "Solomon Islands",
    code: "SB",
    flag: "https://flagcdn.com/sb.svg",
    geoNameId: 2103350,
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    flag: "https://flagcdn.com/sj.svg",
    geoNameId: 607072,
  },
  {
    name: "Faroe Islands",
    code: "FO",
    flag: "https://flagcdn.com/fo.svg",
    geoNameId: 2622320,
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    flag: "https://flagcdn.com/uz.svg",
    geoNameId: 1512440,
  },
  {
    name: "Egypt",
    code: "EG",
    flag: "https://flagcdn.com/eg.svg",
    geoNameId: 357994,
  },
  {
    name: "Senegal",
    code: "SN",
    flag: "https://flagcdn.com/sn.svg",
    geoNameId: 2245662,
  },
  {
    name: "Sri Lanka",
    code: "LK",
    flag: "https://flagcdn.com/lk.svg",
    geoNameId: 1227603,
  },
  {
    name: "Palestine",
    code: "PS",
    flag: "https://flagcdn.com/ps.svg",
    geoNameId: 6254930,
  },
  {
    name: "Bangladesh",
    code: "BD",
    flag: "https://flagcdn.com/bd.svg",
    geoNameId: 1210997,
  },
  {
    name: "Peru",
    code: "PE",
    flag: "https://flagcdn.com/pe.svg",
    geoNameId: 3932488,
  },
  {
    name: "Singapore",
    code: "SG",
    flag: "https://flagcdn.com/sg.svg",
    geoNameId: 1880251,
  },
  {
    name: "Turkey",
    code: "TR",
    flag: "https://flagcdn.com/tr.svg",
    geoNameId: 298795,
  },
  {
    name: "Afghanistan",
    code: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    geoNameId: 1149361,
  },
  {
    name: "Aruba",
    code: "AW",
    flag: "https://flagcdn.com/aw.svg",
    geoNameId: 3577279,
  },
  {
    name: "Cook Islands",
    code: "CK",
    flag: "https://flagcdn.com/ck.svg",
    geoNameId: 1899402,
  },
  {
    name: "United Kingdom",
    code: "GB",
    flag: "https://flagcdn.com/gb.svg",
    geoNameId: 2635167,
  },
  {
    name: "Zambia",
    code: "ZM",
    flag: "https://flagcdn.com/zm.svg",
    geoNameId: 895949,
  },
  {
    name: "Finland",
    code: "FI",
    flag: "https://flagcdn.com/fi.svg",
    geoNameId: 660013,
  },
  {
    name: "Niger",
    code: "NE",
    flag: "https://flagcdn.com/ne.svg",
    geoNameId: 2440476,
  },
  {
    name: "Christmas Island",
    code: "CX",
    flag: "https://flagcdn.com/cx.svg",
    geoNameId: 2078138,
  },
  {
    name: "Tokelau",
    code: "TK",
    flag: "https://flagcdn.com/tk.svg",
    geoNameId: 4031074,
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    flag: "https://flagcdn.com/gw.svg",
    geoNameId: 2372248,
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    flag: "https://flagcdn.com/az.svg",
    geoNameId: 587116,
  },
  {
    name: "Réunion",
    code: "RE",
    flag: "https://flagcdn.com/re.svg",
    geoNameId: 935317,
  },
  {
    name: "Djibouti",
    code: "DJ",
    flag: "https://flagcdn.com/dj.svg",
    geoNameId: 223816,
  },
  {
    name: "North Korea",
    code: "KP",
    flag: "https://flagcdn.com/kp.svg",
    geoNameId: 1873107,
  },
  {
    name: "Mauritius",
    code: "MU",
    flag: "https://flagcdn.com/mu.svg",
    geoNameId: 934292,
  },
  {
    name: "Montserrat",
    code: "MS",
    flag: "https://flagcdn.com/ms.svg",
    geoNameId: 3578097,
  },
  {
    name: "United States Virgin Islands",
    code: "VI",
    flag: "https://flagcdn.com/vi.svg",
    geoNameId: 4796775,
  },
  {
    name: "Colombia",
    code: "CO",
    flag: "https://flagcdn.com/co.svg",
    geoNameId: 3686110,
  },
  {
    name: "Greece",
    code: "GR",
    flag: "https://flagcdn.com/gr.svg",
    geoNameId: 390903,
  },
  {
    name: "Croatia",
    code: "HR",
    flag: "https://flagcdn.com/hr.svg",
    geoNameId: 3202326,
  },
  {
    name: "Morocco",
    code: "MA",
    flag: "https://flagcdn.com/ma.svg",
    geoNameId: 2542007,
  },
  {
    name: "Algeria",
    code: "DZ",
    flag: "https://flagcdn.com/dz.svg",
    geoNameId: 2589581,
  },
  {
    name: "Antarctica",
    code: "AQ",
    flag: "https://flagcdn.com/aq.svg",
    geoNameId: 6697173,
  },
  {
    name: "Netherlands",
    code: "NL",
    flag: "https://flagcdn.com/nl.svg",
    geoNameId: 2750405,
  },
  {
    name: "Sudan",
    code: "SD",
    flag: "https://flagcdn.com/sd.svg",
    geoNameId: 366755,
  },
  {
    name: "Fiji",
    code: "FJ",
    flag: "https://flagcdn.com/fj.svg",
    geoNameId: 2205218,
  },
  {
    name: "Liechtenstein",
    code: "LI",
    flag: "https://flagcdn.com/li.svg",
    geoNameId: 3042058,
  },
  {
    name: "Nepal",
    code: "NP",
    flag: "https://flagcdn.com/np.svg",
    geoNameId: 1282988,
  },
  {
    name: "Puerto Rico",
    code: "PR",
    flag: "https://flagcdn.com/pr.svg",
    geoNameId: 4566966,
  },
  {
    name: "Georgia",
    code: "GE",
    flag: "https://flagcdn.com/ge.svg",
    geoNameId: 614540,
  },
  {
    name: "Pakistan",
    code: "PK",
    flag: "https://flagcdn.com/pk.svg",
    geoNameId: 1168579,
  },
  {
    name: "Monaco",
    code: "MC",
    flag: "https://flagcdn.com/mc.svg",
    geoNameId: 2993457,
  },
  {
    name: "Botswana",
    code: "BW",
    flag: "https://flagcdn.com/bw.svg",
    geoNameId: 933860,
  },
  {
    name: "Lebanon",
    code: "LB",
    flag: "https://flagcdn.com/lb.svg",
    geoNameId: 272103,
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    flag: "https://flagcdn.com/pg.svg",
    geoNameId: 2088628,
  },
  {
    name: "Mayotte",
    code: "YT",
    flag: "https://flagcdn.com/yt.svg",
    geoNameId: 1024031,
  },
  {
    name: "Dominican Republic",
    code: "DO",
    flag: "https://flagcdn.com/do.svg",
    geoNameId: 3508796,
  },
  {
    name: "Norfolk Island",
    code: "NF",
    flag: "https://flagcdn.com/nf.svg",
    geoNameId: 2155115,
  },
  {
    name: "Bouvet Island",
    code: "BV",
    flag: "https://flagcdn.com/bv.svg",
    geoNameId: 3371123,
  },
  {
    name: "Qatar",
    code: "QA",
    flag: "https://flagcdn.com/qa.svg",
    geoNameId: 289688,
  },
  {
    name: "Madagascar",
    code: "MG",
    flag: "https://flagcdn.com/mg.svg",
    geoNameId: 1062947,
  },
  {
    name: "India",
    code: "IN",
    flag: "https://flagcdn.com/in.svg",
    geoNameId: 1269750,
  },
  {
    name: "Syria",
    code: "SY",
    flag: "https://flagcdn.com/sy.svg",
    geoNameId: 163843,
  },
  {
    name: "Montenegro",
    code: "ME",
    flag: "https://flagcdn.com/me.svg",
    geoNameId: 3194884,
  },
  {
    name: "Eswatini",
    code: "SZ",
    flag: "https://flagcdn.com/sz.svg",
    geoNameId: 934841,
  },
  {
    name: "Paraguay",
    code: "PY",
    flag: "https://flagcdn.com/py.svg",
    geoNameId: 3437598,
  },
  {
    name: "El Salvador",
    code: "SV",
    flag: "https://flagcdn.com/sv.svg",
    geoNameId: 3585968,
  },
  {
    name: "Ukraine",
    code: "UA",
    flag: "https://flagcdn.com/ua.svg",
    geoNameId: 690791,
  },
  {
    name: "Isle of Man",
    code: "IM",
    flag: "https://flagcdn.com/im.svg",
    geoNameId: 3042225,
  },
  {
    name: "Namibia",
    code: "NA",
    flag: "https://flagcdn.com/na.svg",
    geoNameId: 3355338,
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    flag: "https://flagcdn.com/ae.svg",
    geoNameId: 290557,
  },
  {
    name: "Bulgaria",
    code: "BG",
    flag: "https://flagcdn.com/bg.svg",
    geoNameId: 732800,
  },
  {
    name: "Greenland",
    code: "GL",
    flag: "https://flagcdn.com/gl.svg",
    geoNameId: 3425505,
  },
  {
    name: "Germany",
    code: "DE",
    flag: "https://flagcdn.com/de.svg",
    geoNameId: 2921044,
  },
  {
    name: "Cambodia",
    code: "KH",
    flag: "https://flagcdn.com/kh.svg",
    geoNameId: 1831722,
  },
  {
    name: "Iraq",
    code: "IQ",
    flag: "https://flagcdn.com/iq.svg",
    geoNameId: 99237,
  },
  {
    name: "French Southern and Antarctic Lands",
    code: "TF",
    flag: "https://flagcdn.com/tf.svg",
    geoNameId: 1546748,
  },
  {
    name: "Sweden",
    code: "SE",
    flag: "https://flagcdn.com/se.svg",
    geoNameId: 2661886,
  },
  {
    name: "Cuba",
    code: "CU",
    flag: "https://flagcdn.com/cu.svg",
    geoNameId: 3562981,
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    flag: "https://flagcdn.com/kg.svg",
    geoNameId: 1527747,
  },
  {
    name: "Russia",
    code: "RU",
    flag: "https://flagcdn.com/ru.svg",
    geoNameId: 2017370,
  },
  {
    name: "Malaysia",
    code: "MY",
    flag: "https://flagcdn.com/my.svg",
    geoNameId: 1733045,
  },
  {
    name: "São Tomé and Príncipe",
    code: "ST",
    flag: "https://flagcdn.com/st.svg",
    geoNameId: 2410758,
  },
  {
    name: "Cyprus",
    code: "CY",
    flag: "https://flagcdn.com/cy.svg",
    geoNameId: 146669,
  },
  {
    name: "Canada",
    code: "CA",
    flag: "https://flagcdn.com/ca.svg",
    geoNameId: 6251999,
  },
  {
    name: "Malawi",
    code: "MW",
    flag: "https://flagcdn.com/mw.svg",
    geoNameId: 927384,
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    flag: "https://flagcdn.com/sa.svg",
    geoNameId: 102358,
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    flag: "https://flagcdn.com/ba.svg",
    geoNameId: 3277605,
  },
  {
    name: "Ethiopia",
    code: "ET",
    flag: "https://flagcdn.com/et.svg",
    geoNameId: 337996,
  },
  {
    name: "Spain",
    code: "ES",
    flag: "https://flagcdn.com/es.svg",
    geoNameId: 2510769,
  },
  {
    name: "Slovenia",
    code: "SI",
    flag: "https://flagcdn.com/si.svg",
    geoNameId: 3190538,
  },
  {
    name: "Oman",
    code: "OM",
    flag: "https://flagcdn.com/om.svg",
    geoNameId: 286963,
  },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    flag: "https://flagcdn.com/pm.svg",
    geoNameId: 3424932,
  },
  {
    name: "Macau",
    code: "MO",
    flag: "https://flagcdn.com/mo.svg",
    geoNameId: 1821275,
  },
  {
    name: "San Marino",
    code: "SM",
    flag: "https://flagcdn.com/sm.svg",
    geoNameId: 3168068,
  },
  {
    name: "Lesotho",
    code: "LS",
    flag: "https://flagcdn.com/ls.svg",
    geoNameId: 932692,
  },
  {
    name: "Marshall Islands",
    code: "MH",
    flag: "https://flagcdn.com/mh.svg",
    geoNameId: 2080185,
  },
  {
    name: "Sint Maarten",
    code: "SX",
    flag: "https://flagcdn.com/sx.svg",
    geoNameId: 7609695,
  },
  {
    name: "Iceland",
    code: "IS",
    flag: "https://flagcdn.com/is.svg",
    geoNameId: 2629691,
  },
  {
    name: "Luxembourg",
    code: "LU",
    flag: "https://flagcdn.com/lu.svg",
    geoNameId: 2960313,
  },
  {
    name: "Argentina",
    code: "AR",
    flag: "https://flagcdn.com/ar.svg",
    geoNameId: 3865483,
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    flag: "https://flagcdn.com/tc.svg",
    geoNameId: 3576916,
  },
  {
    name: "Nauru",
    code: "NR",
    flag: "https://flagcdn.com/nr.svg",
    geoNameId: 2110425,
  },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    flag: "https://flagcdn.com/cc.svg",
    geoNameId: 1547376,
  },
  {
    name: "Western Sahara",
    code: "EH",
    flag: "https://flagcdn.com/eh.svg",
    geoNameId: 2461445,
  },
  {
    name: "Dominica",
    code: "DM",
    flag: "https://flagcdn.com/dm.svg",
    geoNameId: 3575830,
  },
  {
    name: "Costa Rica",
    code: "CR",
    flag: "https://flagcdn.com/cr.svg",
    geoNameId: 3624060,
  },
  {
    name: "Australia",
    code: "AU",
    flag: "https://flagcdn.com/au.svg",
    geoNameId: 2077456,
  },
  {
    name: "Thailand",
    code: "TH",
    flag: "https://flagcdn.com/th.svg",
    geoNameId: 1605651,
  },
  {
    name: "Haiti",
    code: "HT",
    flag: "https://flagcdn.com/ht.svg",
    geoNameId: 3723988,
  },
  {
    name: "Tuvalu",
    code: "TV",
    flag: "https://flagcdn.com/tv.svg",
    geoNameId: 2110297,
  },
  {
    name: "Honduras",
    code: "HN",
    flag: "https://flagcdn.com/hn.svg",
    geoNameId: 3608932,
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    flag: "https://flagcdn.com/gq.svg",
    geoNameId: 2309096,
  },
  {
    name: "Saint Lucia",
    code: "LC",
    flag: "https://flagcdn.com/lc.svg",
    geoNameId: 3576468,
  },
  {
    name: "French Polynesia",
    code: "PF",
    flag: "https://flagcdn.com/pf.svg",
    geoNameId: 4030656,
  },
  {
    name: "Belarus",
    code: "BY",
    flag: "https://flagcdn.com/by.svg",
    geoNameId: 630336,
  },
  {
    name: "Latvia",
    code: "LV",
    flag: "https://flagcdn.com/lv.svg",
    geoNameId: 458258,
  },
  {
    name: "Palau",
    code: "PW",
    flag: "https://flagcdn.com/pw.svg",
    geoNameId: 1559582,
  },
  {
    name: "Guadeloupe",
    code: "GP",
    flag: "https://flagcdn.com/gp.svg",
    geoNameId: 3579143,
  },
  {
    name: "Philippines",
    code: "PH",
    flag: "https://flagcdn.com/ph.svg",
    geoNameId: 1694008,
  },
  {
    name: "Gibraltar",
    code: "GI",
    flag: "https://flagcdn.com/gi.svg",
    geoNameId: 2411586,
  },
  {
    name: "Denmark",
    code: "DK",
    flag: "https://flagcdn.com/dk.svg",
    geoNameId: 2623032,
  },
  {
    name: "Cameroon",
    code: "CM",
    flag: "https://flagcdn.com/cm.svg",
    geoNameId: 2233387,
  },
  {
    name: "Guinea",
    code: "GN",
    flag: "https://flagcdn.com/gn.svg",
    geoNameId: 2420477,
  },
  {
    name: "Bahrain",
    code: "BH",
    flag: "https://flagcdn.com/bh.svg",
    geoNameId: 290291,
  },
  {
    name: "Suriname",
    code: "SR",
    flag: "https://flagcdn.com/sr.svg",
    geoNameId: 3382998,
  },
  {
    name: "DR Congo",
    code: "CD",
    flag: "https://flagcdn.com/cd.svg",
    geoNameId: 203312,
  },
  {
    name: "Somalia",
    code: "SO",
    flag: "https://flagcdn.com/so.svg",
    geoNameId: 51537,
  },
  {
    name: "Czechia",
    code: "CZ",
    flag: "https://flagcdn.com/cz.svg",
    geoNameId: 3077311,
  },
  {
    name: "New Caledonia",
    code: "NC",
    flag: "https://flagcdn.com/nc.svg",
    geoNameId: 2139685,
  },
  {
    name: "Vanuatu",
    code: "VU",
    flag: "https://flagcdn.com/vu.svg",
    geoNameId: 2134431,
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    flag: "https://flagcdn.com/sh.svg",
    geoNameId: 3370751,
  },
  {
    name: "Togo",
    code: "TG",
    flag: "https://flagcdn.com/tg.svg",
    geoNameId: 2363686,
  },
  {
    name: "British Virgin Islands",
    code: "VG",
    flag: "https://flagcdn.com/vg.svg",
    geoNameId: 3577718,
  },
  {
    name: "Kenya",
    code: "KE",
    flag: "https://flagcdn.com/ke.svg",
    geoNameId: 192950,
  },
  {
    name: "Niue",
    code: "NU",
    flag: "https://flagcdn.com/nu.svg",
    geoNameId: 4036232,
  },
  {
    name: "Heard Island and McDonald Islands",
    code: "HM",
    flag: "https://flagcdn.com/hm.svg",
    geoNameId: 1547314,
  },
  {
    name: "Rwanda",
    code: "RW",
    flag: "https://flagcdn.com/rw.svg",
    geoNameId: 49518,
  },
  {
    name: "Estonia",
    code: "EE",
    flag: "https://flagcdn.com/ee.svg",
    geoNameId: 453733,
  },
  {
    name: "Romania",
    code: "RO",
    flag: "https://flagcdn.com/ro.svg",
    geoNameId: 798549,
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    flag: "https://flagcdn.com/tt.svg",
    geoNameId: 3573591,
  },
  {
    name: "Guyana",
    code: "GY",
    flag: "https://flagcdn.com/gy.svg",
    geoNameId: 3378535,
  },
  {
    name: "Timor-Leste",
    code: "TL",
    flag: "https://flagcdn.com/tl.svg",
    geoNameId: 1966436,
  },
  {
    name: "Vietnam",
    code: "VN",
    flag: "https://flagcdn.com/vn.svg",
    geoNameId: 1562822,
  },
  {
    name: "Uruguay",
    code: "UY",
    flag: "https://flagcdn.com/uy.svg",
    geoNameId: 3439705,
  },
  {
    name: "Vatican City",
    code: "VA",
    flag: "https://flagcdn.com/va.svg",
    geoNameId: 3164670,
  },
  {
    name: "Hong Kong",
    code: "HK",
    flag: "https://flagcdn.com/hk.svg",
    geoNameId: 1819730,
  },
  {
    name: "Austria",
    code: "AT",
    flag: "https://flagcdn.com/at.svg",
    geoNameId: 2782113,
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    flag: "https://flagcdn.com/ag.svg",
    geoNameId: 3576396,
  },
  {
    name: "Turkmenistan",
    code: "TM",
    flag: "https://flagcdn.com/tm.svg",
    geoNameId: 1218197,
  },
  {
    name: "Mozambique",
    code: "MZ",
    flag: "https://flagcdn.com/mz.svg",
    geoNameId: 1036973,
  },
  {
    name: "Panama",
    code: "PA",
    flag: "https://flagcdn.com/pa.svg",
    geoNameId: 3703430,
  },
  {
    name: "Micronesia",
    code: "FM",
    flag: "https://flagcdn.com/fm.svg",
    geoNameId: 2081918,
  },
  {
    name: "Ireland",
    code: "IE",
    flag: "https://flagcdn.com/ie.svg",
    geoNameId: 2963597,
  },
  {
    name: "Curaçao",
    code: "CW",
    flag: "https://flagcdn.com/cw.svg",
    geoNameId: 7626836,
  },
  {
    name: "French Guiana",
    code: "GF",
    flag: "https://flagcdn.com/gf.svg",
    geoNameId: 3381670,
  },
  {
    name: "Norway",
    code: "NO",
    flag: "https://flagcdn.com/no.svg",
    geoNameId: 3144096,
  },
  {
    name: "Åland Islands",
    code: "AX",
    flag: "https://flagcdn.com/ax.svg",
    geoNameId: 661882,
  },
  {
    name: "Central African Republic",
    code: "CF",
    flag: "https://flagcdn.com/cf.svg",
    geoNameId: 239880,
  },
  {
    name: "Burkina Faso",
    code: "BF",
    flag: "https://flagcdn.com/bf.svg",
    geoNameId: 2361809,
  },
  {
    name: "Eritrea",
    code: "ER",
    flag: "https://flagcdn.com/er.svg",
    geoNameId: 338010,
  },
  {
    name: "Tanzania",
    code: "TZ",
    flag: "https://flagcdn.com/tz.svg",
    geoNameId: 149590,
  },
  {
    name: "South Korea",
    code: "KR",
    flag: "https://flagcdn.com/kr.svg",
    geoNameId: 1835841,
  },
  {
    name: "Jordan",
    code: "JO",
    flag: "https://flagcdn.com/jo.svg",
    geoNameId: 248816,
  },
  {
    name: "Mauritania",
    code: "MR",
    flag: "https://flagcdn.com/mr.svg",
    geoNameId: 2378080,
  },
  {
    name: "Lithuania",
    code: "LT",
    flag: "https://flagcdn.com/lt.svg",
    geoNameId: 597427,
  },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    flag: "https://flagcdn.com/um.svg",
    geoNameId: 5854968,
  },
  {
    name: "Slovakia",
    code: "SK",
    flag: "https://flagcdn.com/sk.svg",
    geoNameId: 3057568,
  },
  {
    name: "Angola",
    code: "AO",
    flag: "https://flagcdn.com/ao.svg",
    geoNameId: 3351879,
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    flag: "https://flagcdn.com/kz.svg",
    geoNameId: 1522867,
  },
  {
    name: "Moldova",
    code: "MD",
    flag: "https://flagcdn.com/md.svg",
    geoNameId: 617790,
  },
  {
    name: "Mali",
    code: "ML",
    flag: "https://flagcdn.com/ml.svg",
    geoNameId: 2453866,
  },
  {
    name: "Falkland Islands",
    code: "FK",
    flag: "https://flagcdn.com/fk.svg",
    geoNameId: 3474414,
  },
  {
    name: "Armenia",
    code: "AM",
    flag: "https://flagcdn.com/am.svg",
    geoNameId: 174982,
  },
  {
    name: "Samoa",
    code: "WS",
    flag: "https://flagcdn.com/ws.svg",
    geoNameId: 4034894,
  },
  {
    name: "Jersey",
    code: "JE",
    flag: "https://flagcdn.com/je.svg",
    geoNameId: 3042142,
  },
  {
    name: "Japan",
    code: "JP",
    flag: "https://flagcdn.com/jp.svg",
    geoNameId: 1861060,
  },
  {
    name: "Bolivia",
    code: "BO",
    flag: "https://flagcdn.com/bo.svg",
    geoNameId: 3923057,
  },
  {
    name: "Chile",
    code: "CL",
    flag: "https://flagcdn.com/cl.svg",
    geoNameId: 3895114,
  },
  {
    name: "United States",
    code: "US",
    flag: "https://flagcdn.com/us.svg",
    geoNameId: 6252001,
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    flag: "https://flagcdn.com/vc.svg",
    geoNameId: 3577815,
  },
  {
    name: "Bermuda",
    code: "BM",
    flag: "https://flagcdn.com/bm.svg",
    geoNameId: 3573345,
  },
  {
    name: "Seychelles",
    code: "SC",
    flag: "https://flagcdn.com/sc.svg",
    geoNameId: 241170,
  },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    flag: "https://flagcdn.com/io.svg",
    geoNameId: 1282588,
  },
  {
    name: "Guatemala",
    code: "GT",
    flag: "https://flagcdn.com/gt.svg",
    geoNameId: 3595528,
  },
  {
    name: "Ecuador",
    code: "EC",
    flag: "https://flagcdn.com/ec.svg",
    geoNameId: 3658394,
  },
  {
    name: "Martinique",
    code: "MQ",
    flag: "https://flagcdn.com/mq.svg",
    geoNameId: 3570311,
  },
  {
    name: "Tajikistan",
    code: "TJ",
    flag: "https://flagcdn.com/tj.svg",
    geoNameId: 1220409,
  },
  {
    name: "Malta",
    code: "MT",
    flag: "https://flagcdn.com/mt.svg",
    geoNameId: 2562770,
  },
  {
    name: "Gambia",
    code: "GM",
    flag: "https://flagcdn.com/gm.svg",
    geoNameId: 2413451,
  },
  {
    name: "Nigeria",
    code: "NG",
    flag: "https://flagcdn.com/ng.svg",
    geoNameId: 2328926,
  },
  {
    name: "Bahamas",
    code: "BS",
    flag: "https://flagcdn.com/bs.svg",
    geoNameId: 3572887,
  },
  {
    name: "Kosovo",
    code: "XK",
    flag: "https://flagcdn.com/xk.svg",
    geoNameId: 831053,
  },
  {
    name: "Kuwait",
    code: "KW",
    flag: "https://flagcdn.com/kw.svg",
    geoNameId: 285570,
  },
  {
    name: "Maldives",
    code: "MV",
    flag: "https://flagcdn.com/mv.svg",
    geoNameId: 1282028,
  },
  {
    name: "South Sudan",
    code: "SS",
    flag: "https://flagcdn.com/ss.svg",
    geoNameId: 7909807,
  },
  {
    name: "Iran",
    code: "IR",
    flag: "https://flagcdn.com/ir.svg",
    geoNameId: 130758,
  },
  {
    name: "Albania",
    code: "AL",
    flag: "https://flagcdn.com/al.svg",
    geoNameId: 783754,
  },
  {
    name: "Brazil",
    code: "BR",
    flag: "https://flagcdn.com/br.svg",
    geoNameId: 3469034,
  },
  {
    name: "Serbia",
    code: "RS",
    flag: "https://flagcdn.com/rs.svg",
    geoNameId: 6290252,
  },
  {
    name: "Belize",
    code: "BZ",
    flag: "https://flagcdn.com/bz.svg",
    geoNameId: 3582678,
  },
  {
    name: "Myanmar",
    code: "MM",
    flag: "https://flagcdn.com/mm.svg",
    geoNameId: 1327865,
  },
  {
    name: "Bhutan",
    code: "BT",
    flag: "https://flagcdn.com/bt.svg",
    geoNameId: 1252634,
  },
  {
    name: "Venezuela",
    code: "VE",
    flag: "https://flagcdn.com/ve.svg",
    geoNameId: 3625428,
  },
  {
    name: "Liberia",
    code: "LR",
    flag: "https://flagcdn.com/lr.svg",
    geoNameId: 2275384,
  },
  {
    name: "Jamaica",
    code: "JM",
    flag: "https://flagcdn.com/jm.svg",
    geoNameId: 3489940,
  },
  {
    name: "Poland",
    code: "PL",
    flag: "https://flagcdn.com/pl.svg",
    geoNameId: 798544,
  },
  {
    name: "Cayman Islands",
    code: "KY",
    flag: "https://flagcdn.com/ky.svg",
    geoNameId: 3580718,
  },
  {
    name: "Brunei",
    code: "BN",
    flag: "https://flagcdn.com/bn.svg",
    geoNameId: 1820814,
  },
  {
    name: "Comoros",
    code: "KM",
    flag: "https://flagcdn.com/km.svg",
    geoNameId: 921929,
  },
  {
    name: "Guam",
    code: "GU",
    flag: "https://flagcdn.com/gu.svg",
    geoNameId: 4043988,
  },
  {
    name: "Tonga",
    code: "TO",
    flag: "https://flagcdn.com/to.svg",
    geoNameId: 4032283,
  },
  {
    name: "Kiribati",
    code: "KI",
    flag: "https://flagcdn.com/ki.svg",
    geoNameId: 4030945,
  },
  {
    name: "Ghana",
    code: "GH",
    flag: "https://flagcdn.com/gh.svg",
    geoNameId: 2300660,
  },
  {
    name: "Chad",
    code: "TD",
    flag: "https://flagcdn.com/td.svg",
    geoNameId: 2434508,
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    flag: "https://flagcdn.com/zw.svg",
    geoNameId: 878675,
  },
  {
    name: "Saint Martin",
    code: "MF",
    flag: "https://flagcdn.com/mf.svg",
    geoNameId: 3578421,
  },
  {
    name: "Mongolia",
    code: "MN",
    flag: "https://flagcdn.com/mn.svg",
    geoNameId: 2029969,
  },
  {
    name: "Portugal",
    code: "PT",
    flag: "https://flagcdn.com/pt.svg",
    geoNameId: 2264397,
  },
  {
    name: "American Samoa",
    code: "AS",
    flag: "https://flagcdn.com/as.svg",
    geoNameId: 5880801,
  },
  {
    name: "Republic of the Congo",
    code: "CG",
    flag: "https://flagcdn.com/cg.svg",
    geoNameId: 2260494,
  },
  {
    name: "Belgium",
    code: "BE",
    flag: "https://flagcdn.com/be.svg",
    geoNameId: 2802361,
  },
  {
    name: "Israel",
    code: "IL",
    flag: "https://flagcdn.com/il.svg",
    geoNameId: 294640,
  },
  {
    name: "New Zealand",
    code: "NZ",
    flag: "https://flagcdn.com/nz.svg",
    geoNameId: 2186224,
  },
  {
    name: "Nicaragua",
    code: "NI",
    flag: "https://flagcdn.com/ni.svg",
    geoNameId: 3617476,
  },
  {
    name: "Anguilla",
    code: "AI",
    flag: "https://flagcdn.com/ai.svg",
    geoNameId: 3573511,
  },
];
